#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=jeedom

# Source app helpers
	source /usr/share/yunohost/helpers

# Retrieve arguments
	domain=$(ynh_app_setting_get "$app" domain)
	path=$(ynh_app_setting_get "$app" path)
	admin=$(ynh_app_setting_get "$app" admin)
	sudo=$(ynh_app_setting_get "$app" sudo)
	zwave=$(ynh_app_setting_get "$app" zwave)
	dbname=${app}
	dbuser=${app}
	dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
	
# Copy the app source files
	DESTDIR="/var/www/$app"
	ynh_backup "$DESTDIR" "www"
	
# Copy the conf files
	mkdir ./conf
	ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "conf/nginx.conf"
	ynh_backup "/etc/cron.d/${app}" "conf/cron"

# Dump the database
	mysqldump -u "$dbuser" -p"$dbpass" --no-create-db "$dbname" > ./db.sql
