#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
#ip=$3

sudo yunohost app checkurl $domain$path -a jeedom
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

#sudo apt-get install php5-gd php5-sqlite

final_path=/var/www/jeedom

# Configure Nginx and reload
sudo sed -i "s@PATHTOCHANGE@$path@g"  ../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/jeedom.conf
sudo service nginx reload
