#!/bin/bash
app=jeedom

# Source app helpers
	source /usr/share/yunohost/helpers

# Retrieve arguments
	domain=$(ynh_app_setting_get "$app" domain)
	path=$(ynh_app_setting_get "$app" path)
	admin=$(ynh_app_setting_get "$app" admin)
	sudo=$(ynh_app_setting_get "$app" sudo)
	zwave=$(ynh_app_setting_get "$app" zwave)
	dbname=${app}
	dbuser=${app}
	dbpass=$(ynh_app_setting_get "$app" mysqlpwd)

# Remove sources
	sudo rm -rf "/var/www/${app}"
	sudo rm -f "/etc/cron.d/${app}"
	[[ -n $domain ]] && sudo rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# TBD: Remove OZW
	if [ "$zwave" = "Yes" ]; then
	
	fi

# Remove www-data sudoer
	if [ "$sudo" = "Yes" ]; then
		if [ $(sudo grep "www-data ALL=(ALL) NOPASSWD: ALL" /etc/sudoers | wc -l) -eq 0 ];then
			sudo sed -i "/www-data ALL=(ALL) NOPASSWD: ALL/d" /etc/sudoers
		fi
	fi

# Drop MySQL database and user
	ynh_mysql_drop_db "$dbname" 2>/dev/null || true
	ynh_mysql_drop_user "$dbuser" 2>/dev/null || true

# Restart services
	sudo service php5-fpm restart || true
	sudo service nginx reload || true

# Remove app dependencies
	ynh_package_autoremove "$DEPS_PKG_NAME" || true
