#!/bin/bash
app=jeedom

# Source app helpers
	source /usr/share/yunohost/helpers

# Retrieve arguments
	domain=$(ynh_app_setting_get "$app" domain)
	path=$(ynh_app_setting_get "$app" path)
	admin=$(ynh_app_setting_get "$app" admin)

# Remove sources
	sudo rm -rf "/var/www/${app}"
	sudo rm -f "/etc/cron.d/${app}"
	[[ -n $domain ]] && sudo rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Drop MySQL database and user
	ynh_mysql_drop_db "$dbname" 2>/dev/null || true
	ynh_mysql_drop_user "$dbuser" 2>/dev/null || true

# Restart services
	sudo service php5-fpm restart || true
	sudo service nginx reload || true

# Remove app dependencies
	ynh_package_autoremove "$DEPS_PKG_NAME" || true
