#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=jeedom

# The parameter $1 is the uncompressed restore directory location
	backup_dir=$1/apps/$app

# Restore sources & data
	sudo cp -a $backup_dir/sources/. /var/www/$app

# Restore permissions to app files
	sudo chmod 775 -R $final_path
	sudo chown -R www-data:www-data $final_path

# Restore mysql database
	db_pwd=$(sudo yunohost app setting $app mysqlpwd)
	sudo mysql -u $app -p$db_pwd $app < $backup_dir/$app.dmp

# Restore Nginx and YunoHost parameters
	sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
	domain=$(sudo yunohost app setting $app domain)
	sudo cp -a $backup_dir/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Restart webserver
	sudo service nginx reload
