#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=jeedom

# Source app helpers
	source /usr/share/yunohost/helpers

# Retrieve arguments
	domain=$(ynh_app_setting_get "$app" domain)
	path=$(ynh_app_setting_get "$app" path)
	admin=$(ynh_app_setting_get "$app" admin)
	sudo=$(ynh_app_setting_get "$app" sudo)
	zwave=$(ynh_app_setting_get "$app" zwave)
	dbname=${app}
	dbuser=${app}
	dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
	
# Check domain/path availability
	sudo yunohost app checkurl $domain$path -a ${app} \
	|| (echo "Path not available: $domain$path" && exit 1)
	
# Check destination directory
	$final_path="/var/www/$app"
	[[ -d $final_path ]] && ynh_die \
	"The destination directory '$final_path' already exists.\
	 You should safely delete it before restoring this app."

# Check configuration files
	nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
	[[ -f $nginx_conf ]] && ynh_die \
	"The NGINX configuration already exists at '${nginx_conf}'.
	 You should safely delete it before restoring this app."
	 
# Restore the app files
	sudo cp -a ./www "$final_path"
	sudo cp -a ./conf/nginx.conf "$nginx_conf"
	sudo cp -a ./config/cron "/etc/cron.d/${app}"
	
# Create and restore the database
	ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"
	ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" < ./db.sql

# TBD: Reinstall OpenZWave dependencies

# Restore permissions to app files
	sudo chmod 775 -R $final_path
	sudo chown -R www-data:www-data $final_path

# Restore sudo permissions to www-data if agreed to
	if [ "$sudo" = "Yes" ]; then
		if [ $(sudo grep "www-data ALL=(ALL) NOPASSWD: ALL" /etc/sudoers | wc -l) -eq 0 ];then
			sudo bash -c 'echo "www-data ALL=(ALL) NOPASSWD: ALL" | (EDITOR="tee -a" visudo)'
		fi
	fi
	
# Reload services
	sudo service php5-fpm restart || true
	sudo service nginx reload || true
