#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=jeedom
version='2.1.1'

# Retrieve arguments
	domain=$(sudo yunohost app setting $app domain)
	path=$(sudo yunohost app setting $app path)
	admin=$(sudo yunohost app setting $app admin)

# Remove trailing "/" for next commands
	path=${path%/}
	
# Copy of sources files
	final_path=/var/www/$app
	sudo mkdir -p $final_path
	sudo unzip -qq ../sources/core-$version.zip
	sudo cp -a core-$version/. $final_path
	sudo cp -a ../sources/. $final_path
	
# Set permissions to app files
	sudo chmod 775 -R $final_path
	sudo chown -R www-data:www-data $final_path

# Nginx
	sudo sed -i "s@PATHTOCHANGE@$path@g"  ../conf/nginx.conf
	sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/jeedom.conf

# Access to API without SSO
	sudo yunohost app setting $app unprotected_uris -v "/core/api/jeeApi.php"

# Restart services
	sudo service nginx reload
	sudo yunohost app ssowatconf
