#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=jeedom
version='2.1.1'

# Retrieve arguments
	domain=$(sudo yunohost app setting $app domain)
	path=$(sudo yunohost app setting $app path)
	admin=$(sudo yunohost app setting $app admin)
	db_user=$app
	db_pwd=$(sudo yunohost app setting $app mysqlpwd)

# Remove trailing "/" for next commands
	path=${path%/}
	
# Copy of sources files
	final_path=/var/www/$app
	sudo mkdir -p $final_path
	sudo unzip -qq ../sources/core-$version.zip
	sudo cp -a core-$version/. $final_path
	
# Set permissions to app files
	sudo chmod 775 -R $final_path
	sudo chown -R www-data:www-data $final_path

# Configure Jeedom database and initialize app
	sudo cp $final_path/core/config/common.config.sample.php $final_path/core/config/common.config.php
	sudo sed -i -e "s/#HOST#/localhost/g" $final_path/core/config/common.config.php
	sudo sed -i -e "s/#PORT#/3306/g" $final_path/core/config/common.config.php
	sudo sed -i -e "s/#DBNAME#/${db_user}/g" $final_path/core/config/common.config.php
	sudo sed -i -e "s/#USERNAME#/${db_user}/g" $final_path/core/config/common.config.php
	sudo sed -i -e "s/#PASSWORD#/${db_pwd}/g" $final_path/core/config/common.config.php
	sudo chown www-data:www-data $final_path/core/config/common.config.php
	
# Nginx
	sudo sed -i "s@PATHTOCHANGE@$path@g"  ../conf/nginx.conf
	sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/jeedom.conf

# Access to API without SSO
	sudo yunohost app setting $app unprotected_uris -v "/core/api/jeeApi.php"

# Restart services
	sudo service nginx reload
	sudo yunohost app ssowatconf
